# Generated by Django 3.1.2 on 2021-04-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='icon_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
