# Generated by Django 3.1.2 on 2021-02-25 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210225_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='四桁の数字を入力してください。', regex='^[0-9]{4}')]),
        ),
    ]
