# Generated by Django 3.1.2 on 2021-04-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_training_icon_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamboard',
            name='join_count',
            field=models.IntegerField(default=1),
        ),
    ]
