# Generated by Django 3.1.2 on 2021-04-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teamboard_join_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='load',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamboard',
            name='join_count',
            field=models.IntegerField(default=0),
        ),
    ]
