# Generated by Django 3.1.2 on 2021-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210417_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_anyone_join',
            field=models.BooleanField(default=True),
        ),
    ]
